name: mapbox_place_search_example
description: A comprehensive example app demonstrating the Mapbox autocomplete place search plugin.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.8.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mapbox_autocomplete_place_search:
    path: ../
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
